spring:
  config:
    activate:
      on-profile: [ dev ]

  thymeleaf.prefix: file:src/main/resources/templates/

  datasource:
    url: jdbc:mysql://mysql-demo.docker:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root

app:
  label: dev0
