# production system properties

spring:
  config:
    activate:
      on-profile: [ prod ]

  datasource:
    url: jdbc:mysql://mysql-demo.docker:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root

  application:
    name: prod0
